version: '3.8'

services:
  database_ignite:
    image: postgres
    container_name: postegresSQL
    restart: always
    ports: [5432:5432]
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=postgresql_docker
      - POSTGRES_DB=cars
    volumes:
    - pgdata:/data/postgres
  app:
    build: .
    container_name: cars
    ports:
      - 3400:3400
    volumes:
      - .:/usr/app
    links:
      - database_ignite
    depends_on:
      - database_ignite

volumes:
  pgdata:
    driver: local